/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CheckoutCourseIdRouteImport } from './routes/checkout.$courseId'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as InstructorsInstructorIdRouteImport } from './routes/instructors.$instructorId'
import { Route as LearnCourseIdRouteImport } from './routes/learn.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCourseIdRoute = CheckoutCourseIdRouteImport.update({
  id: '/checkout/$courseId',
  path: '/checkout/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsInstructorIdRoute = InstructorsInstructorIdRouteImport.update({
  id: '/instructors/$instructorId',
  path: '/instructors/$instructorId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseIdRoute = LearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructors/$instructorId': typeof InstructorsInstructorIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructors/$instructorId': typeof InstructorsInstructorIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/checkout/$courseId': typeof CheckoutCourseIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/instructors/$instructorId': typeof InstructorsInstructorIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/profile'
    | '/checkout/$courseId'
    | '/courses/$courseId'
    | '/instructors/$instructorId'
    | '/learn/$courseId'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/profile'
    | '/checkout/$courseId'
    | '/courses/$courseId'
    | '/instructors/$instructorId'
    | '/learn/$courseId'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/profile'
    | '/checkout/$courseId'
    | '/courses/$courseId'
    | '/instructors/$instructorId'
    | '/learn/$courseId'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  CheckoutCourseIdRoute: typeof CheckoutCourseIdRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  InstructorsInstructorIdRoute: typeof InstructorsInstructorIdRoute
  LearnCourseIdRoute: typeof LearnCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$courseId': {
      id: '/checkout/$courseId'
      path: '/checkout/$courseId'
      fullPath: '/checkout/$courseId'
      preLoaderRoute: typeof CheckoutCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors/$instructorId': {
      id: '/instructors/$instructorId'
      path: '/instructors/$instructorId'
      fullPath: '/instructors/$instructorId'
      preLoaderRoute: typeof InstructorsInstructorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$courseId': {
      id: '/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof LearnCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  CheckoutCourseIdRoute: CheckoutCourseIdRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  InstructorsInstructorIdRoute: InstructorsInstructorIdRoute,
  LearnCourseIdRoute: LearnCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
